{{- if eq .Values.integration_test false -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "gnomad-blog.fullname" . }}
  labels:
    {{- include "gnomad-blog.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secrets_cluster_secretstore_name }}
  target:
    name: {{ include "gnomad-blog.fullname" . }}-oauth-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
  - extract:
      key: {{ .Values.gcp_blog_oauth_secrets_name }}
{{- end }}
