{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gnomad-legacy-redirects.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gnomad-legacy-redirects.labels" . | nindent 4 }}
  annotations:
    ingress.gcp.kubernetes.io/managed-certificates: {{ include "gnomad-legacy-redirects.fullname" . }}
    networking.gke.io/v1beta1.FrontendConfig: {{ include "gnomad-legacy-redirects.fullname" . }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ include "gnomad-legacy-redirects.fullname" . }}
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "gnomad-legacy-redirects.fullname" . }}
spec:
  domains:
    - {{ .Values.ingress.host | quote}}
{{- end }}
