apiVersion: v1
kind: Service
metadata:
  name: {{ include "gnomad-legacy-redirects.fullname" . }}
  labels:
    {{- include "gnomad-legacy-redirects.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gnomad-legacy-redirects.selectorLabels" . | nindent 4 }}
