# Default values for gnomad-legacy-redirects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/exac-gnomad/legacy-redirects
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

gcp_global_ip: "0.0.0.0"

ingress:
  enabled: true
  host: exac.broadinstitute.org
  paths:
    - path: /*
      pathType: ImplementationSpecific

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 32Mi

nodeSelector:
  {}
  # cloud.google.com/gke-nodepool: main-pool

tolerations: []

affinity: {}
