# Default values for gnomad-legacy-redirects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

imagePullSecrets: []

podAnnotations: {}

image:
  repository: gcr.io/exac-gnomad/legacy-redirects
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 80

gcp_global_ip:
  address: "34.36.116.121"
  name: prod-legacy-redirects-ip

ingress:
  enabled: true
  host: exac.broadinstitute.org
  # managed_cert defaults to false to ease testing. Set to true for prod deployments
  managed_cert: false
  paths:
    - path: /*
      pathType: ImplementationSpecific

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 32Mi

nodeSelector:
  {}
  # cloud.google.com/gke-nodepool: main-pool

affinity: {}

tolerations: []
