apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exome-results-browsers.fullname" . }}
  labels:
    {{- include "exome-results-browsers.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "exome-results-browsers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "exome-results-browsers.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RESULTS_DATA_DIRECTORY
              value: {{ .Values.results_data_disk.mountpoint }}/{{ .Values.results_data_disk.directory }}
            - name: TRUST_PROXY
              value: {{ .Values.env.trust_proxy | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
          {{- if eq .Values.integration_test false }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.results_data_disk.mountpoint }}
          volumes:
            - name: data
              gcePersistentDisk:
                fsType: ext4
                pdName: {{ .Values.results_data_disk.pdName }}
                readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if eq .Values.integration_test false }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
